### ISSUE TITLE
Non-trivial dependencies should be optional

### ISSUE THREAD

**Issue by devnote-dev** [ralsina/tartrazine#10]
I was quite confused to see `docopt`, `stumpy_core`, `stumpy_png` and `stumpy_utils` being installed with Tartrazine, shards that I'm familiar with that wouldn't make sense for a library 🤔. I then discovered the first is for using the shard as an application and the latter for extensions. Realistically such shards shouldn't be required dependencies given they aren't trivial for Tartrazine to operate. Usually if an extension is to be used, it's explicitly `require`d in the user's code at which point it's their responsibility to add the relevant shard(s) as dependencies.

**Comment by ralsina** [comment]
If you use tartrazine as a library, they are NOT linked in your program
unless you pass specific -D options when building.

If you are building the tartrazine binary, it will NOT be linked to those
libraries unless you build it passing the same -D option.

Or at least that's the idea, if it's not working I will fix it.

**Comment by ralsina** [comment]
Unless your code uses the image formatter none of those libraries gets linked to your code AFAIK.

If they do, I will fix it.

**Comment by ralsina** [comment]
AFAICS, it works properly.

I tested it with markterm, which links tartrazine but uses only the Ansi formatter

* stumpy_png/stumpy_core don't link any external libraries
* if you don't use the Png formatter, stumpy is not even built
* docopt is only used by the tartrazine CLI binary, if you use tartrazine as a library it's not even built
* the resulting binary has no stumpy symbols in it

This is the output of `nm bin/tartrazine` which does use the Png formatter and therefor has stumpy built into it:

![image](https://github.com/user-attachments/assets/7bc5bad7-f07f-42a5-b42f-779c878a0eb0)


And here is the output of `nm bin/markterm` which doesn't use the Png formatter and doesn't have any stumpy in it:

![image](https://github.com/user-attachments/assets/44f12310-1116-403f-854b-809cb776c0ba)

So, it's optional and only used when needed.

**Comment by devnote-dev** [comment]
I'm aware that they are not included in the binary, that would be a separate issue. My point is that optional dependencies shouldn't be installed as if they are required. This principle goes well beyond Crystal/Shards and is widely accepted in the developer space.

**Comment by ralsina** [comment]
Sorry, no. They are not installed anywhere except in the lib/ directory when building from source. AFAIK shards don' t provide support for "optional dependencies".

This costs the user nothing and makes exactly zero difference to anyone not using the Png writer.
