### ISSUE TITLE
Crystal highlight heredoc issue

### ISSUE THREAD

**Issue by mamantoha** [ralsina/tartrazine#2]
Sample code with heredoc:

```crystal
lexer = Tartrazine.lexer(name: "crystal")
theme = Tartrazine.theme("github-dark")

source = %Q[
xml = <<-XML
  <person id="1">
    <firstName preferredName="Jane">Jehanne</firstname>
    <lastName>Doe</lastname>
  </person>
XML
]

formatter = Tartrazine::Html.new(theme)
formatter.standalone = true

puts formatter.format(source, lexer)
```

GitHub format it correctly as is:

```crystal
xml = <<-XML
  <person id="1">
    <firstName preferredName="Jane">Jehanne</firstname>
    <lastName>Doe</lastname>
  </person>
XML
```

```
crystal test.cr > index.html
```

Result  from Tatranize:

![image](https://github.com/user-attachments/assets/45a1bad8-8a0e-44a5-90c0-d9a92d4959bc)

**Comment by ralsina** [comment]
A quick look seems to indicate the crystal lexer from chroma has no support
for heredocs. I will try to add it.

**Comment by ralsina** [comment]
Hmmm actually it does. Will do some testing.

<rule pattern="(?&lt;!\w)(&lt;&lt;-?)([&#34;`\&#39;
]?)([a-zA-Z_]\w*)(\2)(.*?\n)">
<token type="LiteralStringHeredoc"/>
</rule>
<rule pattern="(&lt;&lt;-?)(&#34;|\&#39;)()(\2)(.*?\n)">
<token type="LiteralStringHeredoc"/>
</rule>

**Comment by ralsina** [comment]
Seems something got lost in the pygments -> chroma translation

![image](https://github.com/user-attachments/assets/8ca81f5a-7c62-4e50-bb6e-b4800d7f807c)

In pygments, heredocs have a callback, so the support in chroma seems to not be great and tartrazine inherited that.

I had a vague plan to special-case crystal to use the compiler's built-in highlighter, I guess it's needed :-)

**Comment by ralsina** [comment]
I just pushed a PR to try using the native crystal highlighter. It's not a **great** match for the model tartrazine uses but it seems to work :-)

**Comment by ralsina** [comment]
After some testing #3 looks pretty good (or at least no worse than the chroma-based lexer) so I am merging that and closing this issue. Feel free to reopen if you find this new lexer buggy.
