### ISSUE TITLE
Older release tags confuses Shards

### ISSUE THREAD

**Issue by devnote-dev** [ralsina/tartrazine#4]
As far as I can tell, the Tartrazine _shard_ only has releases from `0.1.0` to `0.7.0`, however the existing release tags in the repository go up way past `2.0.0`. I'm not entirely sure what these older releases are but it means that, unless you pin Tartrazine to a specific version, there's no way to reliably install it.

**Comment by ralsina** [comment]
That's a mixup for an experimental branch using a git subtree that brought
all the other tags.

I'll clean it up.

**Comment by ralsina** [comment]
Fixed.
