### ISSUE TITLE
the lexer version example code in readme not work.

### ISSUE THREAD

**Issue by zw963** [ralsina/tartrazine#6]
thanks.

**Comment by wardahub-design** [comment]
try this

https://mega.nz/file/1vkGlJTL#yU-SJLlIilF0mx5qwpPOd3BM8iKZqOJLEQUStR76rrQ

you may need to install the c compiler

**Comment by ralsina** [comment]
Now that was weird. It failed because of the space in `Html.new (`

Anyway, fixed, thanks for the report!

**Comment by zw963** [comment]
> Now that was weird, Now that was weird. It failed because of the space in Html.new

Meet too, i create a [issue](https://github.com/crystal-lang/crystal/issues/15015) for this.
